version: '3'

services:
  demo:
    build:
      context: .
      dockerfile: Demo.Dockerfile
    restart: always
    ports:
      - "8000:8000"
  demo-site:
    build:
      context: ./demo-site/
    restart: on-failure
    ports:
      - "80:80"